### ISSUE TITLE
does not work with standoff 2 version 0.30.3

### ISSUE THREAD

**Issue by Limon4ik349** [Michel-M-code/Metadata-Decryptor#2]
the decrypted metadata does not differ from the usual one

**Comment by SerdarAD** [comment]
Easy can be fixed: 
`change valid = actual - reference - last_actual_value_found + last_reference_value_found < 1_000_000` to `valid = actual - reference - last_actual_value_found + last_reference_value_found < 1_000_000 and size > 0`

**Comment by SerdarAD** [comment]
If you read the error message, you can see that it says that **value not in range** because value is less that zero.
So fix is:
change `valid = actual - reference - last_actual_value_found + last_reference_value_found < 1_000_000` to `valid = actual - reference - last_actual_value_found + last_reference_value_found < 1_000_000 and size > 0` and that's it.

**Comment by SerdarAD** [comment]
If you read the error message, you can see that it says that value not in range because value is less that zero.
So the fix is:
change `valid = actual - reference - last_actual_value_found + last_reference_value_found < 1_000_000` to `valid = actual - reference - last_actual_value_found + last_reference_value_found < 1_000_000 and size > 0`

**Comment by Limon4ik349** [comment]
> If you read the error message, you can see that it says that value not in range because value is less that zero. So the fix is: change `valid = actual - reference - last_actual_value_found + last_reference_value_found < 1_000_000` to `valid = actual - reference - last_actual_value_found + last_reference_value_found < 1_000_000 and size > 0`

the script does not produce any errors, it simply does not decrypt the metadata, leaving it as the original one

**Comment by Limon4ik349** [comment]
solved
